### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by nic-ong** [GoekeLab/bambu-singlecell-spatial#1]
Hi,

I was trying to click through the links in your git readme linking to tutorials on how to analyze your single-cell or spatial data output from bambu-singlecell-spatial using Seurat, but the links appear to be broken (they link back to https://github.com/GoekeLab/bambu-singlecell-spatial/blob/main). Are the mentioned tutorials available? 

Thanks!

**Comment by andredsim** [comment]
Hi, these branches are not ready for public use yet as we are still testing them. Keep a look out for when we fully release it. Thanks!
